### ISSUE TITLE
Develop the Signup Controller

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#1]
Develop the backend signup route for SkillSync, a critical functionality to enable user registration on our platform. Contributors are tasked with creating a secure and efficient endpoint that handles user signup requests.

Tasks:

1. Design and implement the signup route in the backend, allowing users to register with the following information (check user
schema for reference)
Full Name
Email Address
Password
Integrate robust validation for input data to ensure data integrity and security.

2. Use Jwt token 

3. Use Headers insetad of Cookies

**Comment by dark-dev2475** [comment]
claim

**Comment by aashray374** [comment]
@dark-dev2475 first complete the assigned issue then claim further issues

**Comment by spotnewmoon** [comment]
claim

**Comment by official-ashutosh** [comment]
claim

**Comment by aashray374** [comment]
@spotnewmoon whats your progress?

**Comment by sksingh2005** [comment]
claim
