### ISSUE TITLE
Importance of 🟢

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#19]
Imagine continuously inviting a player while playing a game, only to receive no response because they are offline.

In a multiplayer game, displaying a "Last Online" feature is crucial. To achieve this, you need to add a "last_online" field to the user schema. This field will store a timestamp indicating the time the player was last online.

When the player is online, the "last_online" field should be empty. Otherwise, it will display the time in the format DD-MM-YYYY(HH:MM) (e.g., 16-12-2024(16:06)).

Additionally, you need to create three routes:

One route to mark the player as online.
Another route to mark the player as offline.
And last will retrun the Last Online of a partiular user by taking its id
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) for implementing these routes.

To get your pr merged effortlessly please provide the screenshots of the responses in postman

**Comment by official-ashutosh** [comment]
claim
