### ISSUE TITLE
Gather Some Friends 🫂

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#20]
What's the point of playing a multiplayer game alone?

Imagine playing a multiplayer game where the most enjoyable aspect is the opportunity for even introverted players to make friends easily. To enhance this social element, a feature needs to be implemented that allows users to send friend requests to one another. A user can request another to become friends, and the recipient can either accept or reject the request. This functionality will foster meaningful connections and make the multiplayer experience more engaging for all players.

To solve this issue, you need to create the following routes:

Route for sending a friend request.
Route to accept or reject a particular request.
Route to get all requests.
Route to get the status of a particular request.
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) to implement these routes.

To ensure your PR is merged effortlessly, kindly provide screenshots of the responses in Postman.

**Comment by official-ashutosh** [comment]
claim

**Comment by 07CalC** [comment]
claim
