### ISSUE TITLE
I want to Change Something 📝

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#25]
"Sometimes, we regret the decisions we’ve made in the past, but everyone deserves another chance."

Your task is to create routes that allow users to edit their profiles.
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) to implement these routes.

To ensure your PR is merged effortlessly, kindly provide screenshots of the responses in Postman.

**Comment by Sarvesh0955** [comment]
claim

**Comment by official-ashutosh** [comment]
claim
