### ISSUE TITLE
I Think I Forgot Something 🤔

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#26]
"A strong password is essential in today's digital world, but it's all too easy to forget it sometimes."

Your task is to create a "Forgot Password" route with the following functionalities:

Send a 6-digit verification code to the user's email.
Allow the user to reset their password using the verification code.
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) to implement these routes.

To ensure your PR is merged effortlessly, kindly provide screenshots of the responses in Postman.

**Comment by Sarvesh0955** [comment]
claim

**Comment by official-ashutosh** [comment]
claim
