### ISSUE TITLE
Control Your Anger 🤬

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#27]
"Imagine chatting with someone in the game lobby, and there's an annoying player repeatedly sending requests to join the game. Instead of losing your temper, you should block that idiot"

Your task is to implement a feature that allows a user to:

Temporarily block another user.
Retrieve the list of blocked users.
Unblock a previously blocked user.
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) to implement these routes.

To ensure your PR is merged effortlessly, kindly provide screenshots of the responses in Postman.

**Comment by HGRgamer** [comment]
claim

**Comment by SajalGarg035** [comment]
Claim

**Comment by official-ashutosh** [comment]
claim
