### ISSUE TITLE
Develop the login controller

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#3]
Implement a Sign-in API to enable users to authenticate and access our platform's services securely. This API will serve as the gateway for users to log in using their credentials and obtain the necessary authorization to interact with our system.

Key Requirements:

User Authentication: The API should authenticate users by validating their credentials, such as email and password.
Secure Authentication: Some function are already provided in user models for better and easier implementation, like comparePassword, generateToken etc.
Error Handling: Ensure clear and descriptive error messages for different scenarios (e.g., incorrect credentials, expired session).
Session Management: Implement a mechanism for managing user sessions securely, including session expiration and token generation.
All response needed to be sent in the following JSON format

{
    "result": false,
    "error": "${For debugging}",
    "message": "${Message to be displayed to user as a toast}"
}

**Comment by dark-dev2475** [comment]
claim

**Comment by HGRgamer** [comment]
claim
