### ISSUE TITLE
Lets Play Together 🎮

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#32]
"Imagine being able to invite another player to a game directly, but waiting endlessly for their response can ruin the experience. A smoother invitation system is essential to keep the gameplay engaging and dynamic."

Your task is to implement a game invitation feature using sockets. This feature will allow users to send game requests to other players in real-time, with the server managing the response flow.

Feature Requirements

Sending Game Requests:
A user can send a game request to another player using a socket event.

Handling Responses:
The invited player can respond to the game request in one of the following ways:
Accepted: The request is accepted, and the game can proceed.
Rejected: The player explicitly rejects the request.
In-Game: The player is currently busy and already in another game.
Offline: The invited player is offline.

Timeout Handling:
If no response is received within 10 seconds, the request will automatically be considered rejected.
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) to implement these routes.

To ensure your PR is merged effortlessly, kindly provide screenshots of the responses in Postman.

**Comment by official-ashutosh** [comment]
claim
