### ISSUE TITLE
Unable to find Someone?

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#33]
"Imagine having so many friends in your list that finding a particular one becomes a challenge. Scrolling endlessly is frustrating when you just want to locate someone quickly."

Your task is to implement a search and filter feature for friends. This feature will allow users to search for friends by providing their name or email either partially or fully.
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) to implement these routes.

To ensure your PR is merged effortlessly, kindly provide screenshots of the responses in Postman.

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by rajbir40** [comment]
claim
