### ISSUE TITLE
Lets End the Debate 🗣️

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#34]
"Spending time and energy explaining to your noob friend that they’re, well, a noob, is exhausting. Every game needs a way to separate seasoned players from beginners—and here, it’s the WordScore that does the job."

Your task is to implement a WordScore system, which acts as the parameter for distinguishing experienced players from noobs.

Feature Requirements
Add WordScore to User Schema:

Introduce a wordScore field in the user schema.
The default value should be set to 0 when a user is created.
Create Routes for WordScore Management:

Route 1: Create a route to get the current WordScore of a user.
Route 2: Create a route to increase the WordScore by a specified value.
Route 3: Create a route to decrease the WordScore by a specified value.
Validation:

Ensure the WordScore does not fall below 0.
Add error handling for invalid inputs (e.g., negative increments or decrements).
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) to implement these routes.

To ensure your PR is merged effortlessly, kindly provide screenshots of the responses in Postman.

**Comment by official-ashutosh** [comment]
claim

**Comment by HGRgamer** [comment]
claim

**Comment by muffinboy19** [comment]
nice description sir
