### ISSUE TITLE
No more Timepass

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#38]
"Up to this point, we’ve tackled several features to enhance user interactions, but none have touched the heart of the project—the actual game itself. Now, it’s time to dive into the action and start implementing the game mechanics."

Your task is to create a game room feature that can host up to 6 players, keeping everyone updated whenever someone joins or leaves.

Feature Requirements
Game Room Basics:

Implement a game room that can accommodate a maximum of 6 players.
Each game room will dynamically manage the list of players.
Real-Time Updates:

When a player joins or leaves the room, emit the updated list of current players to all connected clients via socket events.
Socket Events:

Event 1: playerJoined
Triggered when a player successfully joins the room.
Event 2: playerLeft
Triggered when a player leaves the room.
Event 3: updatePlayersList
Emits the updated list of players to all connected clients in the room.
Please follow the architecture outlined in the [README.md](https://github.com/opencodeiiita/WordOut-Backend/) to implement these routes.

To ensure your PR is merged effortlessly, kindly provide screenshots of the responses in Postman.

**Comment by HGRgamer** [comment]
Claim

**Comment by ayush-patel1** [comment]
claim

**Comment by HGRgamer** [comment]
@aashray374 Can you please close the issue
