### ISSUE TITLE
Poor Frontend guys

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#39]
"Your friends are working hard on the frontend, but not all of them understand how the backend works. To help them, you need to create a file that explains all the API routes clearly."

Your task is to create a file named API_ENDPOINTS.md. This file will contain all the details about the backend routes, like what parameters are needed, what information should be in the headers, and examples of responses. This will make it easier for your frontend teammates to connect their code to the backend.

What to Do
Create the File:

Name the file API_ENDPOINTS.md and include it in the project folder.
Document Each API Route:
For every route, provide:

Method: Whether it’s GET, POST, PATCH, etc.
URL: The endpoint path (e.g., /api/users/register).
Purpose: A simple explanation of what the route does.
Headers: Any required headers like Authorization or Content-Type.
Parameters: The data needed in the request body, query, or path.
Example Request: A JSON example of what the frontend should send.
Example Response: Examples of successful and error responses from the server.

**Comment by ayush-patel1** [comment]
claim
