### ISSUE TITLE
Write BoilerPlate code for database connection

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#4]
You have to write boilerPlate code to connet it to mongoDB database

**Comment by dark-dev2475** [comment]
claim

**Comment by spotnewmoon** [comment]
claim

**Comment by dark-dev2475** [comment]
sir please clarify that my pr is  visible to you or not ..  iam not getting any confirmation message at my side

**Comment by aashray374** [comment]
your PRs are visible here but you are not following the PR template given in [PR_TEMPLATE](https://github.com/opencodeiiita/WordOut-Backend/blob/main/PR_TEMPLATE.md)

**Comment by dark-dev2475** [comment]
finally made the correct pr sir please review it

**Comment by aashray374** [comment]
@dark-dev2475 you have also pushed node modules with your code please remove them first
