### ISSUE TITLE
Write the BoilerPlate code

### ISSUE THREAD

**Issue by aashray374** [opencodeiiita/WordOut-Backend#7]
In this issue you have to write the code for creating a server using node and express and you have to also create the User Schema the schema will contain:
1. Name
2. Email
3. Password

**Comment by sksingh2005** [comment]
In this issue we only have to write in server.js file and basic end points or can you specify @aashray374  sir ?

**Comment by sksingh2005** [comment]
claim

**Comment by aashray374** [comment]
Yes you have to only write the basic code in server.js and only the schema for the user

**Comment by dark-dev2475** [comment]
claim

**Comment by bhupesh98** [comment]
Hey @dark-dev2475,
You can raise a PR only after the mentor assigns you the issue. You have to wait till that.

**Comment by Skr-suyash** [comment]
claim

**Comment by sksingh2005** [comment]
claim

**Comment by spotnewmoon** [comment]
claim

**Comment by sksingh2005** [comment]
@aashray374  sir can you once check my pr i have made
